port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 白名单
    type: select
    proxies:
      - 测试节点
      - DIRECT
  - name: 测试节点
    type: select
    use:
      - 测试节点2

proxy-providers:
  测试节点2:
    type: http
    url: http://youtellme
    interval: 3600
    path: ./ARK-HK.yaml
    health-check:
      enable: false
      interval: 600
      url: http://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

rules:
  - GEOIP,CN,DIRECT
  - RULE-SET,telegramcidr,白名单
  - MATCH,白名单
