# tun模式基础设置，注意缩进!
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
  enable: true                   # set true to enable dns (default is false)
  ipv6: false                    # default is false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host      # or fake-ip
  fake-ip-range: 198.18.0.1/16   # if you don't know what it is, don't change it
  use-hosts: true                # lookup hosts and return IP record
  fake-ip-filter:                # fake ip white domain list, aka Always Real IP
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
  nameserver:
    - 223.5.5.5                  # 阿里DNS
    - 114.114.114.114            # 114DNS   
  fallback:                      # concurrent request with nameserver, 
    - 1.1.1.1                    # cloudflare
    - 8.8.8.8                    # google
  fallback-filter: 
    geoip: true                  # default    
    ipcidr:                      # ips in these subnets will be considered polluted
      - 240.0.0.0/4
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true